laser_mapping:
  ros__parameters:
    common.lid_topic: "/rslidar_points"
    common.imu_topic: "/rslidar_imu_data"
    common.time_sync_en: false
    common.time_offset_lidar_to_imu: 0.0
    preprocess.lidar_type: 5
    preprocess.scan_line: 96
    preprocess.timestamp_unit: 0
    preprocess.blind: 0.0
    preprocess.scan_rate: 10
    point_filter_num: 3
    feature_extract_enable: false
    max_iteration: 4
    filter_size_corner: 0.2
    filter_size_surf: 0.2
    filter_size_map: 0.2
    cube_side_length: 200.0
    mapping.acc_cov: 0.1
    mapping.gyr_cov: 0.1
    mapping.b_acc_cov: 0.0001
    mapping.b_gyr_cov: 0.0001
    mapping.fov_degree: 120.0
    mapping.det_range: 200.0
    mapping.extrinsic_est_en: false
    mapping.extrinsic_T: [0.00425, 0.00418, -0.00446]
    mapping.extrinsic_R: [1.0, 0.0, 0.0, 
    			  0.0, 1.0, 0.0, 
    			  0.0, 0.0, 1.0]
    publish.path_en: true
    publish.scan_publish_en: true
    publish.dense_publish_en: true
    publish.scan_bodyframe_pub_en: true
    pcd_save.pcd_save_en: true
    pcd_save.interval: -1
